angular.module('keywords', [])

.component('keywords', {
	templateUrl: 'components/keywords/keywords.html',
	controller: function($scope){
        // Full list of MTG keywords
        $scope.keywordsObject = {
            attach: "To attach an Aura, Equipment, or Fortification to a target permanent.",
            counter: "To negate a spell or ability as it is being cast or activated, preventing it from resolving. Also refers to markers placed on permanents to track effects.",
            exile: "To remove a card from the game. Exiled cards can return depending on effects.",
            fight: "Two creatures deal damage equal to their power to each other.",
            mill: "To put the top card(s) of a player's library into their graveyard.",
            sacrifice: "To put a permanent you control into its owner's graveyard.",
            scry: "To look at the top cards of your library and put any number on the bottom in any order, then the rest on top in any order.",
            tap: "To turn a card sideways to indicate it has been used.",
            untap: "To return a tapped card to its upright position, making it available for use again.",
            deathtouch: "Any amount of damage dealt by a creature with deathtouch is enough to destroy the creature it damages.",
            defender: "A creature with defender cannot attack.",
            "double strike": "A creature with double strike deals both first-strike and regular combat damage.",
            enchant: "Used on Auras to describe the type of permanent they can attach to.",
            equip: "Attaches an Equipment to a target creature you control.",
            "first strike": "A creature with first strike deals combat damage before creatures without first strike.",
            flash: "You may cast the card at any time you could cast an instant.",
            flying: "A creature with flying can only be blocked by creatures with flying or reach.",
            haste: "A creature with haste can attack and tap the turn it enters the battlefield.",
            hexproof: "A creature or permanent with hexproof cannot be the target of spells or abilities your opponents control.",
            indestructible: "A permanent with indestructible cannot be destroyed by damage or effects that say 'destroy'.",
            lifelink: "Damage dealt by a creature or source with lifelink causes its controller to gain that much life.",
            menace: "A creature with menace cannot be blocked except by two or more creatures.",
            protection: "A permanent with protection cannot be damaged, enchanted, equipped, blocked, or targeted by anything with the specified quality.",
            prowess: "Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.",
            reach: "A creature with reach can block creatures with flying.",
            trample: "Excess damage from a creature with trample is dealt to the defending player or planeswalker.",
            vigilance: "A creature with vigilance does not tap when attacking.",
            cascade: "When you cast this spell, exile cards from the top of your library until you exile a nonland card with lesser mana value. You may cast it without paying its mana cost.",
            convoke: "You can tap creatures you control to help pay for this spell’s mana cost.",
            cycling: "You may pay the cycling cost and discard this card to draw a card.",
            dash: "You may cast this creature for its dash cost. If you do, it gains haste, and you return it to your hand at the end of turn.",
            delve: "Each card you exile from your graveyard while casting this spell pays for 1 generic mana.",
            flashback: "You may cast this card from your graveyard for its flashback cost, then exile it.",
            foretell: "You may pay 2 generic mana and exile this card from your hand face down. You may cast it for its foretell cost later.",
            kicker: "You may pay an additional cost as you cast this spell for an added effect.",
            madness: "If you discard this card, you may cast it for its madness cost instead of putting it into your graveyard.",
            morph: "You may cast this card face down as a 2/2 creature for 3 mana. Turn it face up at any time for its morph cost.",
            proliferate: "Choose any number of permanents and/or players with counters, then give each another of those counters.",
            persist: "When this creature dies, if it had no -1/-1 counters on it, return it to the battlefield with a -1/-1 counter.",
            unearth: "Return this card from your graveyard to the battlefield. It gains haste. Exile it at the end of the turn or if it would leave the battlefield.",
            undying: "When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield with a +1/+1 counter.",
            wither: "This creature deals damage to creatures in the form of -1/-1 counters.",
            shroud: "Cannot be the target of any spells or abilities.",
            regenerate: "The next time this creature would be destroyed this turn, instead remove all damage from it and tap it.",
            suspend: "Exile this card with a specified number of time counters. At the start of your upkeep, remove a counter. When the last is removed, cast the card without paying its mana cost.",
            absorb: "Prevents a specified amount of damage dealt to a creature by any source of damage",
            adapt: "Allows this creature to gain +1/+1 counters if it has none",
            affinity: "Reduces the mana cost of a spell by 1 generic mana for each permanent of a specified type you control.",
            afterlife: "When a creature with afterlife dies, its controller creates a specified number of 1/1 black and white Spirit tokens with flying.",
            aftermath: "Allows one half of a split card to be cast from the graveyard, then exiles the card after use.",
            amplify: "As a creature with amplify enters the battlefield, it gains +1/+1 counters based on the number of revealed creature cards in hand that share its type.",
            annihilator: "When a creature with annihilator attacks, the defending player sacrifices a specified number of permanents.",
            ascend: "If a player controls ten or more permanents, they gain 'the city's blessing,' unlocking additional effects on cards with ascend.",
            "aura swap": "Allows exchanging an Aura (with the aura swap) on the battlefield with an Aura in your hand by paying the swap cost.",
            "bands with other": "A limited form of banding, allowing creatures to band only with others sharing a specified quality.",
            "battle cry": "When a creature with battle cry attacks, all other attacking creatures get +1/+0 until the end of the turn.",
            bestow: "Allows an enchantment creature to be cast as an Aura, granting its power, toughness, and abilities to a target. If the enchantment creature/Aura is no longer attached to a target, it becomes a creature.",
            bolster: "Put +1/+1 counters on the creature with the lowest toughness you control.",
            bloodthirst: "A creature with bloodthirst enters the battlefield with +1/+1 counters if an opponent was dealt damage that turn.",
            bushido: "A creature with bushido gets +X/+X until the end of the turn when it blocks or is blocked.",
            buyback: "An additional cost for instants or sorceries; if paid, the card returns to your hand instead of going to the graveyard.",
            champion: "When a creature with champion enters, sacrifice it unless you exile another creature you control. When the creature with champion leaves, return the exiled card to the battlefield.",
            changeling: "This card is all creature types.",
            cipher: "You may exile this spell encoded on a creature you control. Whenever that creature deals combat damage, cast a copy of the encoded spell without paying its mana cost.",
            clash: "Reveal the top card of your deck and compare mana costs with an opponent. The higher cost wins and may trigger effects.",
            conspire: "Tap two untapped creatures you control of the spell's color to copy the spell, and you may choose new targets.",
            crew: "Tap creatures you control with total power at least equal to the crew cost to turn a vehicle into an artifact creature until end of turn.",
            "cumulative upkeep": "At the beginning of your upkeep, add an age counter and pay the cumulative cost for each counter, or sacrifice the card.",
            daybound: "If it is night, transforms to day next turn if a player casts two or more spells during their turn.",
            nightbound: "If it is day, transforms to night next turn if no spells are cast during a player's turn.",
            detain: "The detained permanent cannot attack, block, or activate abilities until the start of the controller's next turn.",
            devour: "When a creature with devour enters the battlefield, its controller may sacrifice creatures to put a specified number of +1/+1 counters on it for each sacrificed creature.",
            dredge: "Instead of drawing, you may put the top x cards of their library into their graveyard to return the dredge card from the graveyard to their hand.",
            echo: "At the beginning of the controller's upkeep after playing the card, pay its echo cost or sacrifice it.",
            embalm: "Exile the creature card from the graveyard for its embalm cost to create a token copy of it, which is a Zombie in addition to its other types.",
            emerge: "Pay an alternate mana cost by sacrificing a creature and paying the difference between the emerge cost and the sacrificed creature's mana cost.",
            entwine: "Pay an additional cost to choose all effects of a spell instead of just one.",
            epic: "After casting, you can no longer cast spells for the rest of the game. However, you copy the epic spell at the start of each of your upkeeps.",
            evolve: "Whenever a creature with higher power or toughness enters the battlefield under your control, put a +1/+1 counter on the creature with evolve.",
            evoke: "Pay an alternate, usually cheaper, cost to cast the creature. Sacrifice it immediately after it enters the battlefield.",
            exalted: "When a creature you control attacks alone, it gets +1/+1 until end of turn for each permanent with exalted you control.",
            exert: "A creature can exert itself when it attacks or activates an ability, gaining a benefit but not untapping during its controller's next untap step.",
            exploit: "When a creature with exploit enters the battlefield, its controller may sacrifice a creature to trigger a specific effect.",
            explore: "Reveal the top card of your library. If it is a land, put it in your hand; otherwise, put a +1/+1 counter on the creature and choose whether to keep the card on top or send it to the graveyard.",
            extort: "When casting a spell, you may pay a white or black mana to make each opponent lose 1 life. You gain life equal to the total life lost.",
            fabricate: "When a creature with fabricate enters the battlefield, choose to put x +1/+1 counters on it or create x 1/1 Servo artifact creature tokens.",
            fading: "A permanent with fading enters the battlefield with x fade counters. Remove one at each upkeep; if none remain, sacrifice it.",
            fateseal: "Look at the top x cards of an opponent's library. You may put any number of them on the bottom of their library and the rest on top of their library in any order.",
            flanking: "When a creature with flanking is blocked by a creature without flanking, the blocking creature gets -1/-1 until end of turn."
        }
        
        // Input value
		$scope.selectKeyword = ""

        // Reset values
        $scope.$on('resetDetails', function() {
            $scope.selectKeyword = ""
        });
	}
})